version: "3.7"

services:
    laravel-test-apache:
        container_name: laravel-test-apache
        hostname: laravel-test-apache
        restart: always
        ports:
            - "9000:80"
        build: .
        volumes:
            - ./src:/var/www/html
        user: root
        depends_on:
            - laravel-test-postgres
        networks:
            - laravel_test_net

    laravel-test-postgres:
        container_name: laravel-test-postgres
        hostname: laravel-test-postgres
        restart: always
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: test
            POSTGRES_USER: test #пользователь при создании базы первом запуске контейнера
            POSTGRES_PASSWORD: test #пароль пользователя при создании базы данных при первом запуске контейнера
            PGUSER: test #пользователь для подключения к базе
            PGPASSWORD: test #пользователь для подключения к базе
        volumes:
            - test-pgdata:/var/lib/postgresql/data
        networks:
            - laravel_test_net

networks:
    laravel_test_net:
        name: laravel_test_net

volumes:
    test-pgdata:
